building a debian package

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -42,6 +42,17 @@ jobs:
           if [ ! -f build/plugins/libros2_tracing_cpp.so ]; then
             echo "Plugin build failed!" && exit 1
           fi
+      
+      - name: Building Debian Package
+        run: |
+          cd build
+          cpack
+
+      - name: Verify Plugins Packaged Successfully
+        run: |
+          if [ ! -f build/libros2_tracing_cpp.deb ]; then
+            echo "Plugin packaging failed!" && exit 1
+          fi
 
       - name: Upload Plugin as Artifact
         uses: actions/upload-artifact@v4
